#############################################################################
# Generated by PAGE version 7.5
#  in conjunction with Tcl version 8.6
#  Mar 27, 2023 12:28:04 AM IST  platform: Windows NT
set vTcl(timestamp) ""
if {![info exists vTcl(borrow)]} {
    ::vTcl::MessageBox -title Error -message  "You must open project files from within PAGE."
    exit}


set image_list { 
}
vTcl:create_project_images $image_list   ;# In image.tcl

if {!$vTcl(borrow) && !$vTcl(template)} {

set vTcl(actual_gui_font_dft_desc)  TkDefaultFont
set vTcl(actual_gui_font_dft_name)  TkDefaultFont
set vTcl(actual_gui_font_text_desc)  TkTextFont
set vTcl(actual_gui_font_text_name)  TkTextFont
set vTcl(actual_gui_font_fixed_desc)  TkFixedFont
set vTcl(actual_gui_font_fixed_name)  TkFixedFont
set vTcl(actual_gui_font_menu_desc)  TkMenuFont
set vTcl(actual_gui_font_menu_name)  TkMenuFont
set vTcl(actual_gui_font_tooltip_desc)  TkDefaultFont
set vTcl(actual_gui_font_tooltip_name)  TkDefaultFont
set vTcl(actual_gui_font_treeview_desc)  TkDefaultFont
set vTcl(actual_gui_font_treeview_name)  TkDefaultFont
########################################### 
set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) gray40
set vTcl(analog_color_p) #c3c3c3
set vTcl(analog_color_m) beige
set vTcl(tabfg1) black
set vTcl(tabfg2) black
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(actual_gui_menu_active_fg)  #000000
########################################### 
set vTcl(pr,autoalias) 1
set vTcl(pr,relative_placement) 1
set vTcl(mode) Relative
}




proc vTclWindow.top1 {base} {
    global vTcl
    if {$base == ""} {
        set base .top1
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    set target $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -menu "$top.m57" -background #51a7ae -highlightbackground #000000 \
        -highlightcolor #000000 
    wm focusmodel $top passive
    wm geometry $top 1366x705+119+28
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1370 749
    wm minsize $top 148 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    set toptitle "Console 1 modified"
    wm title $top $toptitle
    namespace eval ::widgets::${top}::ClassOption {}
    set ::widgets::${top}::ClassOption(-toptitle) $toptitle
    vTcl:DefineAlias "$top" "Toplevel1" vTcl:Toplevel:WidgetProc "" 1
    set vTcl(real_top) {}
    label $top.lab46 \
        -activebackground #ffffff -activeforeground #000000 -anchor w \
        -background #ceb731 -compound left -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 18 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {PCB Fault Detection System} 
    vTcl:DefineAlias "$top.lab46" "Label1" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab49 \
        -activebackground #f9f9f9 -activeforeground SystemButtonText \
        -anchor w -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 14 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {Reference Image} 
    vTcl:DefineAlias "$top.lab49" "Label2" vTcl:WidgetProc "Toplevel1" 1
    menu $top.m57 \
        -activebackground $vTcl(actual_gui_menu_analog) \
        -activeforeground #000000 -background #000000 -font TkMenuFont \
        -foreground $vTcl(actual_gui_menu_fg) -tearoff 0 
    labelframe $top.lab53 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -background $vTcl(actual_gui_bg) -height 466 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -width 620 
    vTcl:DefineAlias "$top.lab53" "Labelframe5_2" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.lab53
    label $site_3_0.lab46 \
        -activebackground #f9f9f9 -activeforeground SystemButtonText \
        -anchor w -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text Label 
    vTcl:DefineAlias "$site_3_0.lab46" "Label3" vTcl:WidgetProc "Toplevel1" 1
    place $site_3_0.lab46 \
        -in $site_3_0 -x 0 -y 0 -width 0 -relwidth 0.99 -height 0 \
        -relheight 1.011 -anchor nw -bordermode ignore 
    button $top.but57 \
        -activebackground $vTcl(analog_color_m) -activeforeground black \
        -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text Button 
    vTcl:DefineAlias "$top.but57" "Button2_2" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab59 \
        -activebackground #f9f9f9 -activeforeground SystemButtonText \
        -anchor w -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 14 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {Test Image} 
    vTcl:DefineAlias "$top.lab59" "Label2_2" vTcl:WidgetProc "Toplevel1" 1
    button $top.but47 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -command RICapture -compound left \
        -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text Capture 
    vTcl:DefineAlias "$top.but47" "Button1_1" vTcl:WidgetProc "Toplevel1" 1
    button $top.but49 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -command RISearch -compound left \
        -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text Search 
    vTcl:DefineAlias "$top.but49" "Button1_1_2" vTcl:WidgetProc "Toplevel1" 1
    button $top.but50 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -command RISet_image -compound left \
        -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text {Set Image} 
    vTcl:DefineAlias "$top.but50" "Button1_1_1" vTcl:WidgetProc "Toplevel1" 1
    button $top.but51 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -command TICapture -compound left \
        -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -highlightbackground #ffffff \
        -highlightcolor black -pady 0 -text Capture 
    vTcl:DefineAlias "$top.but51" "Button1_1_3" vTcl:WidgetProc "Toplevel1" 1
    button $top.but52 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -command TISearch -compound left \
        -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text Search 
    vTcl:DefineAlias "$top.but52" "Button1_1_3_1" vTcl:WidgetProc "Toplevel1" 1
    button $top.but53 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -command TISet_image -compound left \
        -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text {Set Image} 
    vTcl:DefineAlias "$top.but53" "Button1_1_1_1" vTcl:WidgetProc "Toplevel1" 1
    labelframe $top.lab54 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -background $vTcl(actual_gui_bg) -height 466 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -width 612 
    vTcl:DefineAlias "$top.lab54" "Labelframe5_2_2" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.lab54
    label $site_3_0.lab47 \
        -activebackground #f9f9f9 -activeforeground SystemButtonText \
        -anchor w -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text Label 
    vTcl:DefineAlias "$site_3_0.lab47" "Label4" vTcl:WidgetProc "Toplevel1" 1
    place $site_3_0.lab47 \
        -in $site_3_0 -x 0 -y 0 -width 0 -relwidth 1.003 -height 0 \
        -relheight 1.011 -anchor nw -bordermode ignore 
    button $top.but55 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background #800080 -command Con1_Next -compound left \
        -disabledforeground #a3a3a3 -font TkDefaultFont -foreground #ffffff \
        -highlightbackground #ff8040 -highlightcolor black -pady 0 \
        -text {Next Page} 
    vTcl:DefineAlias "$top.but55" "Button1_1_3_3" vTcl:WidgetProc "Toplevel1" 1
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.lab46 \
        -in $top -x 0 -relx 0.403 -y 0 -rely 0.028 -width 0 -relwidth 0.228 \
        -height 0 -relheight 0.068 -anchor nw -bordermode ignore 
    place $top.lab49 \
        -in $top -x 0 -relx 0.19 -y 0 -rely 0.113 -width 0 -relwidth 0.108 \
        -height 0 -relheight 0.044 -anchor nw -bordermode ignore 
    place $top.lab53 \
        -in $top -x 0 -relx 0.029 -y 0 -rely 0.199 -width 0 -relwidth 0.454 \
        -height 0 -relheight 0.661 -anchor nw -bordermode ignore 
    place $top.but57 \
        -in $top -x 0 -relx 0.959 -y 0 -rely 1.22 -width 27 -relwidth 0 \
        -height 24 -relheight 0 -anchor nw -bordermode ignore 
    place $top.lab59 \
        -in $top -x 0 -relx 0.725 -y 0 -rely 0.113 -width 0 -relwidth 0.075 \
        -height 0 -relheight 0.044 -anchor nw -bordermode ignore 
    place $top.but47 \
        -in $top -x 0 -relx 0.395 -y 0 -rely 0.879 -width 57 -relwidth 0 \
        -height 34 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but49 \
        -in $top -x 0 -relx 0.439 -y 0 -rely 0.879 -width 57 -relwidth 0 \
        -height 34 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but50 \
        -in $top -x 0 -relx 0.19 -y 0 -rely 0.879 -width 207 -relwidth 0 \
        -height 34 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but51 \
        -in $top -x 0 -relx 0.886 -y 0 -rely 0.879 -width 57 -relwidth 0 \
        -height 34 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but52 \
        -in $top -x 0 -relx 0.93 -y 0 -rely 0.879 -width 57 -relwidth 0 \
        -height 34 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but53 \
        -in $top -x 0 -relx 0.673 -y 0 -rely 0.879 -width 207 -relwidth 0 \
        -height 34 -relheight 0 -anchor nw -bordermode ignore 
    place $top.lab54 \
        -in $top -x 0 -relx 0.52 -y 0 -rely 0.199 -width 0 -relwidth 0.448 \
        -height 0 -relheight 0.661 -anchor nw -bordermode ignore 
    place $top.but55 \
        -in $top -x 0 -relx 0.886 -y 0 -rely 0.936 -width 117 -relwidth 0 \
        -height 34 -relheight 0 -anchor nw -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

proc vTclWindow.top10 {base} {
    global vTcl
    if {$base == ""} {
        set base .top10
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    set target $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -menu "$top.m57" -background #51a7ae -highlightbackground #000000 \
        -highlightcolor #000000 
    wm focusmodel $top passive
    wm geometry $top 1366x705+-1+29
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1370 749
    wm minsize $top 148 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    set toptitle "Console 2 Modified"
    wm title $top $toptitle
    namespace eval ::widgets::${top}::ClassOption {}
    set ::widgets::${top}::ClassOption(-toptitle) $toptitle
    vTcl:DefineAlias "$top" "Toplevel1_2" vTcl:Toplevel:WidgetProc "" 1
    set vTcl(real_top) {}
    label $top.lab46 \
        -activebackground #ffffff -activeforeground #000000 -anchor w \
        -background #ceb731 -compound left -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 18 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {PCB Fault Detection System} 
    vTcl:DefineAlias "$top.lab46" "Label1_2" vTcl:WidgetProc "Toplevel1_2" 1
    label $top.lab49 \
        -activebackground #f9f9f9 -activeforeground SystemButtonText \
        -anchor w -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 14 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {Reference Image} 
    vTcl:DefineAlias "$top.lab49" "Label2_3" vTcl:WidgetProc "Toplevel1_2" 1
    menu $top.m57 \
        -activebackground $vTcl(actual_gui_menu_analog) \
        -activeforeground #000000 -background #000000 -font TkMenuFont \
        -foreground $vTcl(actual_gui_menu_fg) -tearoff 0 
    labelframe $top.lab53 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -background $vTcl(actual_gui_bg) -height 466 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -width 620 
    vTcl:DefineAlias "$top.lab53" "Labelframe5_2_1" vTcl:WidgetProc "Toplevel1_2" 1
    set site_3_0 $top.lab53
    label $site_3_0.lab48 \
        -activebackground #f9f9f9 -activeforeground SystemButtonText \
        -anchor w -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text Label 
    vTcl:DefineAlias "$site_3_0.lab48" "Label3_1" vTcl:WidgetProc "Toplevel1_2" 1
    place $site_3_0.lab48 \
        -in $site_3_0 -x 0 -y 0 -width 0 -relwidth 1.006 -height 0 \
        -relheight 0.989 -anchor nw -bordermode ignore 
    button $top.but57 \
        -activebackground $vTcl(analog_color_m) -activeforeground black \
        -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text Button 
    vTcl:DefineAlias "$top.but57" "Button2_2_1" vTcl:WidgetProc "Toplevel1_2" 1
    label $top.lab59 \
        -activebackground #f9f9f9 -activeforeground SystemButtonText \
        -anchor w -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 14 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {Analyzed Test Image} 
    vTcl:DefineAlias "$top.lab59" "Label2_2_1" vTcl:WidgetProc "Toplevel1_2" 1
    labelframe $top.lab54 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -background $vTcl(actual_gui_bg) -height 466 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -width 620 
    vTcl:DefineAlias "$top.lab54" "Labelframe5_2_2_1" vTcl:WidgetProc "Toplevel1_2" 1
    set site_3_0 $top.lab54
    label $site_3_0.lab50 \
        -activebackground #f9f9f9 -activeforeground SystemButtonText \
        -anchor w -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text Label 
    vTcl:DefineAlias "$site_3_0.lab50" "Label4_1" vTcl:WidgetProc "Toplevel1_2" 1
    place $site_3_0.lab50 \
        -in $site_3_0 -x 0 -y 0 -width 0 -relwidth 1.003 -height 0 \
        -relheight 0.989 -anchor nw -bordermode ignore 
    button $top.but55 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background #800080 -command Con2_Next -compound left \
        -disabledforeground #a3a3a3 -font TkDefaultFont -foreground #ffffff \
        -highlightbackground #ff8040 -highlightcolor black -pady 0 \
        -text {Next Page} 
    vTcl:DefineAlias "$top.but55" "Button1_1_3_3_1" vTcl:WidgetProc "Toplevel1_2" 1
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.lab46 \
        -in $top -x 0 -relx 0.403 -y 0 -rely 0.028 -width 0 -relwidth 0.228 \
        -height 0 -relheight 0.068 -anchor nw -bordermode ignore 
    place $top.lab49 \
        -in $top -x 0 -relx 0.198 -y 0 -rely 0.113 -width 0 -relwidth 0.108 \
        -height 0 -relheight 0.044 -anchor nw -bordermode ignore 
    place $top.lab53 \
        -in $top -x 0 -relx 0.029 -y 0 -rely 0.199 -width 0 -relwidth 0.454 \
        -height 0 -relheight 0.661 -anchor nw -bordermode ignore 
    place $top.but57 \
        -in $top -x 0 -relx 0.959 -y 0 -rely 1.22 -width 27 -relwidth 0 \
        -height 24 -relheight 0 -anchor nw -bordermode ignore 
    place $top.lab59 \
        -in $top -x 0 -relx 0.688 -y 0 -rely 0.113 -width 0 -relwidth 0.133 \
        -height 0 -relheight 0.044 -anchor nw -bordermode ignore 
    place $top.lab54 \
        -in $top -x 0 -relx 0.52 -y 0 -rely 0.199 -width 0 -relwidth 0.455 \
        -height 0 -relheight 0.661 -anchor nw -bordermode ignore 
    place $top.but55 \
        -in $top -x 0 -relx 0.886 -y 0 -rely 0.894 -width 117 -relwidth 0 \
        -height 34 -relheight 0 -anchor nw -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

proc vTclWindow.top11 {base} {
    global vTcl
    if {$base == ""} {
        set base .top11
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    set target $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -menu "$top.m57" -background #51a7ae -highlightbackground #000000 \
        -highlightcolor #000000 
    wm focusmodel $top passive
    wm geometry $top 1366x705+32+0
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1370 749
    wm minsize $top 148 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    set toptitle "Console 3 Modified"
    wm title $top $toptitle
    namespace eval ::widgets::${top}::ClassOption {}
    set ::widgets::${top}::ClassOption(-toptitle) $toptitle
    vTcl:DefineAlias "$top" "Toplevel1_2_1" vTcl:Toplevel:WidgetProc "" 1
    set vTcl(real_top) {}
    label $top.lab46 \
        -activebackground #ffffff -activeforeground #000000 -anchor w \
        -background #ceb731 -compound left -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 18 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {PCB Fault Detection System} 
    vTcl:DefineAlias "$top.lab46" "Label1_2_1" vTcl:WidgetProc "Toplevel1_2_1" 1
    label $top.lab49 \
        -activebackground #f9f9f9 -activeforeground SystemButtonText \
        -anchor w -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 14 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {Analyzed Test Image} 
    vTcl:DefineAlias "$top.lab49" "Label2_3_1" vTcl:WidgetProc "Toplevel1_2_1" 1
    menu $top.m57 \
        -activebackground $vTcl(actual_gui_menu_analog) \
        -activeforeground #000000 -background #000000 -font TkMenuFont \
        -foreground $vTcl(actual_gui_menu_fg) -tearoff 0 
    labelframe $top.lab53 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -background $vTcl(actual_gui_bg) -height 466 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -width 620 
    vTcl:DefineAlias "$top.lab53" "Labelframe5_2_1_1" vTcl:WidgetProc "Toplevel1_2_1" 1
    set site_3_0 $top.lab53
    label $site_3_0.lab51 \
        -activebackground #f9f9f9 -activeforeground SystemButtonText \
        -anchor w -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text Label 
    vTcl:DefineAlias "$site_3_0.lab51" "Label3_2" vTcl:WidgetProc "Toplevel1_2_1" 1
    place $site_3_0.lab51 \
        -in $site_3_0 -x 0 -y 0 -width 0 -relwidth 0.99 -height 0 \
        -relheight 0.989 -anchor nw -bordermode ignore 
    button $top.but57 \
        -activebackground $vTcl(analog_color_m) -activeforeground black \
        -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text Button 
    vTcl:DefineAlias "$top.but57" "Button2_2_1_1" vTcl:WidgetProc "Toplevel1_2_1" 1
    label $top.lab59 \
        -activebackground #f9f9f9 -activeforeground SystemButtonText \
        -anchor w -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 14 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {Colour Filtered Analyzed Test Image} 
    vTcl:DefineAlias "$top.lab59" "Label2_2_1_1" vTcl:WidgetProc "Toplevel1_2_1" 1
    labelframe $top.lab54 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -background $vTcl(actual_gui_bg) -height 466 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -width 620 
    vTcl:DefineAlias "$top.lab54" "Labelframe5_2_2_1_1" vTcl:WidgetProc "Toplevel1_2_1" 1
    set site_3_0 $top.lab54
    label $site_3_0.lab52 \
        -activebackground #f9f9f9 -activeforeground SystemButtonText \
        -anchor w -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text Label 
    vTcl:DefineAlias "$site_3_0.lab52" "Label4_2" vTcl:WidgetProc "Toplevel1_2_1" 1
    place $site_3_0.lab52 \
        -in $site_3_0 -x 0 -y 0 -width 0 -relwidth 1.003 -height 0 \
        -relheight 0.989 -anchor nw -bordermode ignore 
    button $top.but55 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background #800080 -compound left -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground #ffffff -highlightbackground #ff8040 \
        -highlightcolor black -pady 0 -text {Next Page} 
    vTcl:DefineAlias "$top.but55" "Button1_1_3_3_1_1" vTcl:WidgetProc "Toplevel1_2_1" 1
    button $top.but56 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text Save 
    vTcl:DefineAlias "$top.but56" "Button1_1_4" vTcl:WidgetProc "Toplevel1_2_1" 1
    button $top.but58 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text Save 
    vTcl:DefineAlias "$top.but58" "Button1_1_4_1" vTcl:WidgetProc "Toplevel1_2_1" 1
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.lab46 \
        -in $top -x 0 -relx 0.403 -y 0 -rely 0.028 -width 0 -relwidth 0.228 \
        -height 0 -relheight 0.068 -anchor nw -bordermode ignore 
    place $top.lab49 \
        -in $top -x 0 -relx 0.198 -y 0 -rely 0.113 -width 0 -relwidth 0.13 \
        -height 0 -relheight 0.044 -anchor nw -bordermode ignore 
    place $top.lab53 \
        -in $top -x 0 -relx 0.029 -y 0 -rely 0.199 -width 0 -relwidth 0.454 \
        -height 0 -relheight 0.661 -anchor nw -bordermode ignore 
    place $top.but57 \
        -in $top -x 0 -relx 0.959 -y 0 -rely 1.22 -width 27 -relwidth 0 \
        -height 24 -relheight 0 -anchor nw -bordermode ignore 
    place $top.lab59 \
        -in $top -x 0 -relx 0.644 -y 0 -rely 0.113 -width 0 -relwidth 0.227 \
        -height 0 -relheight 0.044 -anchor nw -bordermode ignore 
    place $top.lab54 \
        -in $top -x 0 -relx 0.52 -y 0 -rely 0.199 -width 0 -relwidth 0.455 \
        -height 0 -relheight 0.661 -anchor nw -bordermode ignore 
    place $top.but55 \
        -in $top -x 0 -relx 0.886 -y 0 -rely 0.936 -width 117 -relwidth 0 \
        -height 34 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but56 \
        -in $top -x 0 -relx 0.439 -y 0 -rely 0.879 -width 57 -relwidth 0 \
        -height 34 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but58 \
        -in $top -x 0 -relx 0.93 -y 0 -rely 0.879 -width 57 -relwidth 0 \
        -height 34 -relheight 0 -anchor nw -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

proc vTclWindow.top12 {base} {
    global vTcl
    if {$base == ""} {
        set base .top12
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    set target $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -menu "$top.m57" -background #51a7ae -highlightbackground #000000 \
        -highlightcolor #000000 
    wm focusmodel $top passive
    wm geometry $top 1366x705+276+40
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1370 749
    wm minsize $top 148 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    set toptitle "Console 4 modified"
    wm title $top $toptitle
    namespace eval ::widgets::${top}::ClassOption {}
    set ::widgets::${top}::ClassOption(-toptitle) $toptitle
    vTcl:DefineAlias "$top" "Toplevel1_3" vTcl:Toplevel:WidgetProc "" 1
    set vTcl(real_top) {}
    label $top.lab46 \
        -activebackground #ffffff -activeforeground #000000 -anchor w \
        -background #ceb731 -compound left -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 18 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {PCB Fault Detection System} 
    vTcl:DefineAlias "$top.lab46" "Label1_3" vTcl:WidgetProc "Toplevel1_3" 1
    label $top.lab49 \
        -activebackground #f9f9f9 -activeforeground SystemButtonText \
        -anchor w -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 14 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {Analyzed Test Image} 
    vTcl:DefineAlias "$top.lab49" "Label2_4" vTcl:WidgetProc "Toplevel1_3" 1
    menu $top.m57 \
        -activebackground $vTcl(actual_gui_menu_analog) \
        -activeforeground #000000 -background #000000 -font TkMenuFont \
        -foreground $vTcl(actual_gui_menu_fg) -tearoff 0 
    labelframe $top.lab53 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -background $vTcl(actual_gui_bg) -height 466 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -width 620 
    vTcl:DefineAlias "$top.lab53" "Labelframe5_2_3" vTcl:WidgetProc "Toplevel1_3" 1
    set site_3_0 $top.lab53
    label $site_3_0.lab53 \
        -activebackground #f9f9f9 -activeforeground SystemButtonText \
        -anchor w -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text Label 
    vTcl:DefineAlias "$site_3_0.lab53" "Label3_3" vTcl:WidgetProc "Toplevel1_3" 1
    place $site_3_0.lab53 \
        -in $site_3_0 -x 0 -y 0 -width 0 -relwidth 0.99 -height 0 \
        -relheight 0.989 -anchor nw -bordermode ignore 
    button $top.but57 \
        -activebackground $vTcl(analog_color_m) -activeforeground black \
        -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text Button 
    vTcl:DefineAlias "$top.but57" "Button2_2_2" vTcl:WidgetProc "Toplevel1_3" 1
    label $top.lab59 \
        -activebackground #f9f9f9 -activeforeground SystemButtonText \
        -anchor w -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 14 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {Live Camera Feed} 
    vTcl:DefineAlias "$top.lab59" "Label2_2_2" vTcl:WidgetProc "Toplevel1_3" 1
    labelframe $top.lab54 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -background $vTcl(actual_gui_bg) -height 466 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -width 620 
    vTcl:DefineAlias "$top.lab54" "Labelframe5_2_2_2" vTcl:WidgetProc "Toplevel1_3" 1
    set site_3_0 $top.lab54
    label $site_3_0.lab54 \
        -activebackground #f9f9f9 -activeforeground SystemButtonText \
        -anchor w -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text Label 
    vTcl:DefineAlias "$site_3_0.lab54" "Label4_3" vTcl:WidgetProc "Toplevel1_3" 1
    place $site_3_0.lab54 \
        -in $site_3_0 -x 0 -y 0 -width 0 -relwidth 0.987 -height 0 \
        -relheight 0.989 -anchor nw -bordermode ignore 
    button $top.but55 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background #800080 -compound left -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground #ffffff -highlightbackground #ff8040 \
        -highlightcolor black -pady 0 -text Close 
    vTcl:DefineAlias "$top.but55" "Button1_1_3_3_2" vTcl:WidgetProc "Toplevel1_3" 1
    entry $top.ent46 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) -insertbackground black -width 214 
    vTcl:DefineAlias "$top.ent46" "Entry1" vTcl:WidgetProc "Toplevel1_3" 1
    button $top.but47 \
        -activebackground $vTcl(analog_color_m) -activeforeground black \
        -background $vTcl(actual_gui_bg) -command Save_firebase \
        -compound left -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text Save 
    vTcl:DefineAlias "$top.but47" "Button1" vTcl:WidgetProc "Toplevel1_3" 1
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.lab46 \
        -in $top -x 0 -relx 0.403 -y 0 -rely 0.028 -width 0 -relwidth 0.228 \
        -height 0 -relheight 0.068 -anchor nw -bordermode ignore 
    place $top.lab49 \
        -in $top -x 0 -relx 0.198 -y 0 -rely 0.113 -width 0 -relwidth 0.13 \
        -height 0 -relheight 0.044 -anchor nw -bordermode ignore 
    place $top.lab53 \
        -in $top -x 0 -relx 0.029 -y 0 -rely 0.199 -width 0 -relwidth 0.454 \
        -height 0 -relheight 0.661 -anchor nw -bordermode ignore 
    place $top.but57 \
        -in $top -x 0 -relx 0.959 -y 0 -rely 1.22 -width 27 -relwidth 0 \
        -height 24 -relheight 0 -anchor nw -bordermode ignore 
    place $top.lab59 \
        -in $top -x 0 -relx 0.71 -y 0 -rely 0.113 -width 0 -relwidth 0.119 \
        -height 0 -relheight 0.044 -anchor nw -bordermode ignore 
    place $top.lab54 \
        -in $top -x 0 -relx 0.52 -y 0 -rely 0.199 -width 0 -relwidth 0.455 \
        -height 0 -relheight 0.661 -anchor nw -bordermode ignore 
    place $top.but55 \
        -in $top -x 0 -relx 0.886 -y 0 -rely 0.894 -width 117 -relwidth 0 \
        -height 34 -relheight 0 -anchor nw -bordermode ignore 
    place $top.ent46 \
        -in $top -x 0 -relx 0.52 -y 0 -rely 0.894 -width 214 -relwidth 0 \
        -height 34 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but47 \
        -in $top -x 0 -relx 0.695 -y 0 -rely 0.894 -width 86 -relwidth 0 \
        -height 33 -relheight 0 -anchor nw -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

proc 36 {args} {return 1}


Window show .
set btop1 ""
if {$vTcl(borrow)} {
    set btop1 .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop1 $vTcl(tops)] != -1} {
        set btop1 .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop1
Window show .top1 $btop1
if {$vTcl(borrow)} {
    $btop1 configure -background plum
}
set btop2 ""
if {$vTcl(borrow)} {
    set btop2 .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop2 $vTcl(tops)] != -1} {
        set btop2 .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop2
Window show .top10 $btop2
if {$vTcl(borrow)} {
    $btop2 configure -background plum
}
set btop3 ""
if {$vTcl(borrow)} {
    set btop3 .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop3 $vTcl(tops)] != -1} {
        set btop3 .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop3
Window show .top11 $btop3
if {$vTcl(borrow)} {
    $btop3 configure -background plum
}
set btop4 ""
if {$vTcl(borrow)} {
    set btop4 .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop4 $vTcl(tops)] != -1} {
        set btop4 .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop4
Window show .top12 $btop4
if {$vTcl(borrow)} {
    $btop4 configure -background plum
}

